### ISSUE TITLE
Get pipeline working on AWS

### ISSUE THREAD

**Issue by drpatelh** [nf-core/proteinfold#16]
### Description of feature

The purpose of this issue is to document the Nextflow/Nextflow Tower settings required to run the pipeline on AWS Batch. As the pipeline matures we can finesse these requirements but it would be good to periodically dump the 2 settings I have outlined below.

If using Tower, you can install and set-up the Tower CLI with the instructions [here](https://github.com/seqeralabs/tower-cli#1-installation):

1. Dump JSON file with settings required to create the AWS Compute Environment

```
tw compute-envs export --name=<COMPUTE_ENV_NAME> --workspace=<ORGANISATION>/<WORKSPACE>
```

2. Dump JSON file with settings required to create the Pipeline in the Launchpad

```
tw pipelines export --name=<PIPELINE_NAME> --workspace=<ORGANISATION>/<WORKSPACE>
```

**Comment by wosmanitx** [comment]
1)

1)
{
  "region" : "us-west-2",
  "executionRole" : "arn:aws:iam:::role/TowerForge--ExecutionRole",
  "cliPath" : "/home/ec2-user/miniconda/bin/aws",
  "workDir" : "s3://",
  "environment" : [ ],
  "forge" : {
    "type" : "SPOT",
    "minCpus" : 0,
    "maxCpus" : 128,
    "gpuEnabled" : true,
    "ebsAutoScale" : true,
    "instanceTypes" : [ "g5.4xlarge" ],
    "imageId" : "ami-",
    "subnets" : [ ],
    "securityGroups" : [ ],
    "disposeOnDeletion" : true,
    "ec2KeyPair" : "development",
    "allowBuckets" : [ "", "" ],
    "fusionEnabled" : true,
    "efsCreate" : false
  },
  "discriminator" : "aws-batch"
}

2)

{
  "launch" : {
    "id" : "",
    "computeEnvId" : "",
    "pipeline" : "https://github.com/athbaltzis/proteinfold",
    "workDir" : "s3://",
    "revision" : "dev",
    "configText" : "process {\n            withName: 'RUN_COLABFOLD' {\n                accelerator = 1\n           }\n        }",
    "resume" : false,
    "pullLatest" : true,
    "stubRun" : false,
    "dateCreated" : "2022-04-06T14:59:00Z"
  }
}

**Comment by athbaltzis** [comment]
I just closed the issue since we managed to run the pipeline on AWS with these settings. If you want to add some more info, please feel free to re-open it.
