### ISSUE TITLE
Installation issues - proteinfold

### ISSUE THREAD

**Issue by pnatarajan9** [nf-core/proteinfold#171]
### Description of the bug

Proteinfold - https://github.com/nf-core/proteinfold

CRITICAL The container "nf-core/proteinfold_alphafold2_msa:1.1.0" is unavailable.                                                                 
         WARNING: Couldn't use cached digest for registry: HEAD https://index.docker.io/v2/nf-core/proteinfold_alphafold2_msa/manifests/1.1.0:    
         unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)                                               
         WARNING: Falling back to direct digest.                                                                                                  
         FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for                                 
         docker://nf-core/proteinfold_alphafold2_msa:1.1.0: GET https://index.docker.io/v2/nf-core/proteinfold_alphafold2_msa/manifests/1.1.0:    
         UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:nf-core/proteinfold_alphafold2_msa Type:repository]]  

### System information

Nextflow version - 23.04.1
nf-core version: 2.7.2
Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-28-generic x86_64)
nf-core proteinfold 1.1.0

**Comment by JoseEspinosa** [comment]
The image is publicly available [here](https://quay.io/repository/nf-core/proteinfold_alphafold2_msa?tab=tags) so should be available. Which command did you used to run the pipeline?

**Comment by pnatarajan9** [comment]
**To answer your question about the command used:**

$ nf-core download proteinfold --outdir dev --singularity-cache-only  --container singularity
? Select release / branch: dev  [release]

If transferring the downloaded files to another system, it can be convenient to have everything compressed in a single file.
This is not recommended when downloading Singularity images, as it can take a long time and saves very little space.
? Choose compression type: none
INFO     Saving 'nf-core/proteinfold'                                                                                            
          Pipeline revision: 'dev'                                                                                               
          Pull containers: 'singularity'                                                                                         
          Using $NXF_SINGULARITY_CACHEDIR': /ccbbcoded/ccbb_software/software/nfcore/singularity                                 
          Output directory: 'dev'                                                                                                
INFO     Downloading workflow files from GitHub                                                                                  
INFO     Downloading centralised configs from GitHub                                                                             
INFO     Found 11 containers                                                                                                     
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  55% • 6/11 completed
nf-core/proteinfold_alphafold2_msa:1.1.0 WARNING: Falling back to direct digest. ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━INFO     Singularity container retrieval failed with the following error:                                                        
INFO     WARNING: Couldn't use cached digest for registry: HEAD                                                                  
         https://index.docker.io/v2/nf-core/proteinfold_alphafold2_msa/manifests/1.1.0: unexpected status code 401 Unauthorized  
         (HEAD responses have no body, use GET for details)                                                                      
         WARNING: Falling back to direct digest.                                                                                 
         FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for                
         docker://nf-core/proteinfold_alphafold2_msa:1.1.0: GET                                                                  
         https://index.docker.io/v2/nf-core/proteinfold_alphafold2_msa/manifests/1.1.0: UNAUTHORIZED: authentication required;   
         [map[Action:pull Class: Name:nf-core/proteinfold_alphafold2_msa Type:repository]]                                       
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  55% • 6/11 completed
nf-core/proteinfold… FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for d… 
CRITICAL The container "nf-core/proteinfold_alphafold2_msa:1.1.0" is unavailable.                                                
         WARNING: Couldn't use cached digest for registry: HEAD                                                                  
         https://index.docker.io/v2/nf-core/proteinfold_alphafold2_msa/manifests/1.1.0: unexpected status code 401 Unauthorized  
         (HEAD responses have no body, use GET for details)                                                                      
         WARNING: Falling back to direct digest.                                                                                 
         FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for                
         docker://nf-core/proteinfold_alphafold2_msa:1.1.0: GET                                                                  
         https://index.docker.io/v2/nf-core/proteinfold_alphafold2_msa/manifests/1.1.0: UNAUTHORIZED: authentication required;   
         [map[Action:pull Class: Name:nf-core/proteinfold_alphafold2_msa Type:repository]]

**Comment by JoseEspinosa** [comment]
First, I will suggest you use a newer version of nf-core, the current version is 2.14.1. You can find documentation on how to do it [here](https://nf-co.re/docs/nf-core-tools/installation#update-tools). Then, the following command should work: `nf-core download proteinfold --outdir dev --container-system singularity`. Let me know if you have any other issues.

**Comment by pnatarajan9** [comment]
I am sorry for the delay in getting back.  
**We had an similar error with the new version of nf-core 2.14.1 **
INFO     Saving 'nf-core/proteinfold'                                                                                                               
          Pipeline revision: 'dev'                                                                                                                  
          Use containers: 'singularity'                                                                                                             
          Container library: 'quay.io'                                                                                                              
          Using $NXF_SINGULARITY_CACHEDIR': /ccbbcoded/ccbb_software/software/nfcore/singularity'                                                   
          Output directory: 'dev'                                                                                                                   
          Include default institutional configuration: 'True'                                                                                       
INFO     Downloading centralised configs from GitHub                                                                                                
INFO     Downloading workflow files from GitHub                                                                                                     
INFO     Processing workflow revision dev, found 11 container images in total.                                                                      
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  55% • 6/11 completed
nf-core/proteinfold_alphafold2_msa:1.1.0 INFO:    Extracting OCI image... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ERROR    "nf-core/proteinfold_alphafold2_msa:1.1.0" failed for unclear reasons.                                                                     
                                                                                                                                                    
INFO     Pulling of "nf-core/proteinfold_alphafold2_msa:1.1.0" failed.                                                                              
         Please troubleshoot the command                                                                                                            
         "singularity pull --name /ccbbcoded/ccbb_software/software/nfcore/singularity/nf-core-proteinfold_alphafold2_msa-1.1.0.img                 
         docker://quay.io/nf-core/proteinfold_alphafold2_msa:1.1.0" manually.                                                                       
                                                                                                                                                    
ERROR    "nf-core/proteinfold_alphafold2_msa:1.1.0" failed for unclear reasons.                                                                     
                                                                                                                                                    
ERROR    Pulling of "nf-core/proteinfold_alphafold2_msa:1.1.0" failed.                                                                              
         Please troubleshoot the command                                                                                                            
         "singularity pull --name /ccbbcoded/ccbb_software/software/nfcore/singularity/nf-core-proteinfold_alphafold2_msa-1.1.0.img                 
         docker://quay.io/nf-core/proteinfold_alphafold2_msa:1.1.0" manually.                                                                       
                                                                                                                                                    
ERROR    Not able to pull image of ('nf-core/proteinfold_alphafold2_msa:1.1.0',                                                                     
         '/ccbbcoded/ccbb_software/software/nfcore/singularity/nf-core-proteinfold_alphafold2_msa-1.1.0.img', None). Service might be down or       
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  64% • 7/11 completed
nf-core/proteinfold_alphafold2_split:1.1.0 INFO:    Extracting OCI image... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ERROR    "nf-core/proteinfold_alphafold2_split:1.1.0" failed for unclear reasons.                                                                   
                                                                                                                                                    
INFO     Pulling of "nf-core/proteinfold_alphafold2_split:1.1.0" failed.                                                                            
         Please troubleshoot the command                                                                                                            
         "singularity pull --name /ccbbcoded/ccbb_software/software/nfcore/singularity/nf-core-proteinfold_alphafold2_split-1.1.0.img               
         docker://quay.io/nf-core/proteinfold_alphafold2_split:1.1.0" manually.                                                                     
                                                                                                                                                    
ERROR    "nf-core/proteinfold_alphafold2_split:1.1.0" failed for unclear reasons.                                                                   
                                                                                                                                                    
ERROR    Pulling of "nf-core/proteinfold_alphafold2_split:1.1.0" failed.                                                                            
         Please troubleshoot the command                                                                                                            
         "singularity pull --name /ccbbcoded/ccbb_software/software/nfcore/singularity/nf-core-proteinfold_alphafold2_split-1.1.0.img               
         docker://quay.io/nf-core/proteinfold_alphafold2_split:1.1.0" manually.                                                                     
                                                                                                                                                    
ERROR    Not able to pull image of ('nf-core/proteinfold_alphafold2_split:1.1.0',                                                                   
         '/ccbbcoded/ccbb_software/software/nfcore/singularity/nf-core-proteinfold_alphafold2_split-1.1.0.img', None). Service might be down or     
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━  73% • 8/11 completed
nf-core/proteinfold_alphafold2_standard:1.1.0 INFO:    Extracting OCI image... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ERROR    "nf-core/proteinfold_alphafold2_standard:1.1.0" failed for unclear reasons.                                                                
                                                                                                                                                    
INFO     Pulling of "nf-core/proteinfold_alphafold2_standard:1.1.0" failed.                                                                         
         Please troubleshoot the command                                                                                                            
         "singularity pull --name /ccbbcoded/ccbb_software/software/nfcore/singularity/nf-core-proteinfold_alphafold2_standard-1.1.0.img            
         docker://quay.io/nf-core/proteinfold_alphafold2_standard:1.1.0" manually.                                                                  
                                                                                                                                                    
ERROR    "nf-core/proteinfold_alphafold2_standard:1.1.0" failed for unclear reasons.                                                                
                                                                                                                                                    
ERROR    Pulling of "nf-core/proteinfold_alphafold2_standard:1.1.0" failed.                                                                         
         Please troubleshoot the command                                                                                                            
         "singularity pull --name /ccbbcoded/ccbb_software/software/nfcore/singularity/nf-core-proteinfold_alphafold2_standard-1.1.0.img            
         docker://quay.io/nf-core/proteinfold_alphafold2_standard:1.1.0" manually.                                                                  
                                                                                                                                                    
ERROR    Not able to pull image of ('nf-core/proteinfold_alphafold2_standard:1.1.0',                                                                
         '/ccbbcoded/ccbb_software/software/nfcore/singularity/nf-core-proteinfold_alphafold2_standard-1.1.0.img', None). Service might be down or  
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━  82% • 9/11 completed
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━  82% • 9/11 completed
nf-core/proteinfold_colabfold:1.1.0 INFO:    Extracting OCI image... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Comment by pnatarajan9** [comment]
Update: We were able to install proteinfold with the nf-core version 2.14.1 in different compute environment. Thank you for your help!
