### ISSUE TITLE
Split colabfold_batch command in localcolabfold.nf into two separate, colabfold_search + colabfold_batch, commands

### ISSUE THREAD

**Issue by nfg-interline** [nf-core/proteinfold#20]
### Description of feature

This is related to issue #19, "Add capability for localcolabfold to run vs a locally-hosted database (FSx Lustre or webserver)".  This issue partially blocks that issue, in the case where that issue is resolved through the FSx Lustre approach. 

A version of the workflow should exists, calling an alternative / variant of /modules/local/localcolabfold.nf , wherein the exectuable calls to "colabfold_batch"  (lines 23 and 39 in current nextflow script) should each be split into two distinct executable calls, "colabfold_search" and then "colabfold_batch". 

"colabfold_search" takes an input .fasta sequence and queries it against a locally installed colabfold database, generating an MSA as output.

"colabfold_batch" takes the MSA output generated by "colabfold_search" and runs structural inference on it. 

This split is necessary to be able to run a query using a locally-installed database, rather than against a webserver.

**Comment by athbaltzis** [comment]
Fixed by the PR #23
