### ISSUE TITLE
Change input field from samplesheet from "sequence" to "id"

### ISSUE THREAD

**Issue by luisas** [nf-core/proteinfold#200]
### Description of feature

In most of the pipelines is used as "id" and is also stored in meta as "id". I find it a bit confusing - maybe it is better to use id from the beginning.

**Comment by luisas** [comment]
Test dataset PR: https://github.com/nf-core/test-datasets/pull/1362

**Comment by luisas** [comment]
#205

**Comment by JoseEspinosa** [comment]
Closed in #205
