### ISSUE TITLE
colabfold - No module named 'openmm'

### ISSUE THREAD

**Issue by Nicobouch** [nf-core/proteinfold#99]
### Description of the bug

Error with colabfold

### Command used and terminal output

```console
nextflow run proteinfold-dev --input sample_alpha.csv --outdir colabfold_test_multi --use_gpu true --mode colabfold --colabfold_server webserver --num_recycle 3 --colabfold_model_preset alphafold2_multimer_v3 -profile ifb_core

Input file 'sample_alpha.csv' contains two entries
sequence,fasta
prot1,/shared/prot1.fasta
prot2,/shared/prot2.fasta
__________

Traceback (most recent call last):
    File "/localcolabfold/colabfold-conda/bin/colabfold_batch", line 8, in <module>
      sys.exit(main())
    File "/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/batch.py", line 1771, in main
      run(
    File "/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/batch.py", line 1449, in run
      results = predict_structure(
    File "/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/batch.py", line 529, in predict_structure
      pdb_lines = relax_me(pdb_lines=unrelaxed_pdb_lines[key], use_gpu=use_gpu_relax)
    File "/localcolabfold/colabfold-conda/lib/python3.9/site-packages/colabfold/batch.py", line 300, in relax_me
      from alphafold.relax import relax
    File "/localcolabfold/colabfold-conda/lib/python3.9/site-packages/alphafold/relax/relax.py", line 18, in <module>
      from alphafold.relax import amber_minimize
    File "/localcolabfold/colabfold-conda/lib/python3.9/site-packages/alphafold/relax/amber_minimize.py", line 25, in <module>
      from alphafold.relax import cleanup
    File "/localcolabfold/colabfold-conda/lib/python3.9/site-packages/alphafold/relax/cleanup.py", line 23, in <module>
      from openmm import app
  ModuleNotFoundError: No module named 'openmm'
```

**Comment by athbaltzis** [comment]
We are preparing a PR that fixes few bugs (including this one). It will be ready in the next few days

**Comment by athbaltzis** [comment]
Can you confirm that it works now with the above-mentioned PR?

**Comment by Nicobouch** [comment]
Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  usage: colabfold_batch [-h] [--stop-at-score STOP_AT_SCORE]
                         [--num-recycle NUM_RECYCLE]
                         [--recycle-early-stop-tolerance RECYCLE_EARLY_STOP_TOLERANCE]
                         [--num-ensemble NUM_ENSEMBLE] [--num-seeds NUM_SEEDS]
                         [--random-seed RANDOM_SEED] [--num-models {1,2,3,4,5}]
                         [--recompile-padding RECOMPILE_PADDING]
                         [--model-order MODEL_ORDER] [--host-url HOST_URL]
                         [--data DATA]
                         [--msa-mode {mmseqs2_uniref_env,mmseqs2_uniref,single_sequence}]
                         [--model-type {auto,alphafold2,alphafold2_ptm,alphafold2_multimer_v1,alphafold2_multimer_v2,alphafold2_multimer_v3}]
                         [--amber] [--num-relax NUM_RELAX] [--templates]
                         [--custom-template-path CUSTOM_TEMPLATE_PATH]
                         [--rank {auto,plddt,ptm,iptm,multimer}]
                         [--pair-mode {unpaired,paired,unpaired_paired}]
                         [--sort-queries-by {none,length,random}]
                         [--save-single-representations]
                         [--save-pair-representations] [--use-dropout]
                         [--max-seq MAX_SEQ] [--max-extra-seq MAX_EXTRA_SEQ]
                         [--max-msa MAX_MSA] [--disable-cluster-profile] [--zip]
                         [--use-gpu-relax] [--save-all] [--save-recycles]
                         [--overwrite-existing-results]
                         [--disable-unified-memory]
                         input results
  colabfold_batch: error: unrecognized arguments: --cpu

**Comment by athbaltzis** [comment]
The issue with the obselete `--cpu` argument has been fixed. Waiting for your confirmation to close the issue.

**Comment by Nicobouch** [comment]
It works perfectly well now ! thanks !
